# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_ref_clk.xdc

# Block Designs: bd/microblaze_impl/microblaze_impl.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl || ORIG_REF_NAME==microblaze_impl} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_microblaze_0_0/microblaze_impl_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_microblaze_0_0 || ORIG_REF_NAME==microblaze_impl_microblaze_0_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_microblaze_0_axi_periph_0/microblaze_impl_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microblaze_impl_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_microblaze_0_axi_intc_0/microblaze_impl_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_microblaze_0_axi_intc_0 || ORIG_REF_NAME==microblaze_impl_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_microblaze_0_xlconcat_0/microblaze_impl_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_microblaze_0_xlconcat_0 || ORIG_REF_NAME==microblaze_impl_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_mdm_1_0/microblaze_impl_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_mdm_1_0 || ORIG_REF_NAME==microblaze_impl_mdm_1_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_clk_wiz_1_0/microblaze_impl_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_clk_wiz_1_0 || ORIG_REF_NAME==microblaze_impl_clk_wiz_1_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_rst_clk_wiz_1_100M_0/microblaze_impl_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==microblaze_impl_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_dlmb_v10_0/microblaze_impl_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_dlmb_v10_0 || ORIG_REF_NAME==microblaze_impl_dlmb_v10_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_ilmb_v10_0/microblaze_impl_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_ilmb_v10_0 || ORIG_REF_NAME==microblaze_impl_ilmb_v10_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_dlmb_bram_if_cntlr_0/microblaze_impl_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_impl_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_ilmb_bram_if_cntlr_0/microblaze_impl_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_impl_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_lmb_bram_0/microblaze_impl_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_lmb_bram_0 || ORIG_REF_NAME==microblaze_impl_lmb_bram_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_mig_7series_0_0/microblaze_impl_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_mig_7series_0_0 || ORIG_REF_NAME==microblaze_impl_mig_7series_0_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_mii_to_rmii_0_0/microblaze_impl_mii_to_rmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_mii_to_rmii_0_0 || ORIG_REF_NAME==microblaze_impl_mii_to_rmii_0_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_axi_uartlite_0_0/microblaze_impl_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_axi_uartlite_0_0 || ORIG_REF_NAME==microblaze_impl_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_axi_ethernetlite_0_0/microblaze_impl_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_axi_ethernetlite_0_0 || ORIG_REF_NAME==microblaze_impl_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_axi_timer_0_0/microblaze_impl_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_axi_timer_0_0 || ORIG_REF_NAME==microblaze_impl_axi_timer_0_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_axi_smc_0/microblaze_impl_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_axi_smc_0 || ORIG_REF_NAME==microblaze_impl_axi_smc_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_rst_mig_7series_0_81M_0/microblaze_impl_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==microblaze_impl_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/microblaze_impl/ip/microblaze_impl_xbar_0/microblaze_impl_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_impl_xbar_0 || ORIG_REF_NAME==microblaze_impl_xbar_0} -quiet] -quiet

# XDC: bd/microblaze_impl/microblaze_impl_ooc.xdc
