# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/brent/prj_microblaze_nexys4_ddr/prj_microblaze_nexys4_ddr.srcs/sources_1/bd/microblaze_impl/ip/microblaze_impl_axi_ethernetlite_0_0/microblaze_impl_axi_ethernetlite_0_0.xci
# IP: The module: 'microblaze_impl_axi_ethernetlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/brent/prj_microblaze_nexys4_ddr/prj_microblaze_nexys4_ddr.srcs/sources_1/bd/microblaze_impl/ip/microblaze_impl_axi_ethernetlite_0_0/microblaze_impl_axi_ethernetlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_impl_axi_ethernetlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/brent/prj_microblaze_nexys4_ddr/prj_microblaze_nexys4_ddr.srcs/sources_1/bd/microblaze_impl/ip/microblaze_impl_axi_ethernetlite_0_0/microblaze_impl_axi_ethernetlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_impl_axi_ethernetlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/brent/prj_microblaze_nexys4_ddr/prj_microblaze_nexys4_ddr.srcs/sources_1/bd/microblaze_impl/ip/microblaze_impl_axi_ethernetlite_0_0/microblaze_impl_axi_ethernetlite_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_impl_axi_ethernetlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/brent/prj_microblaze_nexys4_ddr/prj_microblaze_nexys4_ddr.srcs/sources_1/bd/microblaze_impl/ip/microblaze_impl_axi_ethernetlite_0_0/microblaze_impl_axi_ethernetlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_impl_axi_ethernetlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/brent/prj_microblaze_nexys4_ddr/prj_microblaze_nexys4_ddr.srcs/sources_1/bd/microblaze_impl/ip/microblaze_impl_axi_ethernetlite_0_0/microblaze_impl_axi_ethernetlite_0_0.xci
# IP: The module: 'microblaze_impl_axi_ethernetlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/brent/prj_microblaze_nexys4_ddr/prj_microblaze_nexys4_ddr.srcs/sources_1/bd/microblaze_impl/ip/microblaze_impl_axi_ethernetlite_0_0/microblaze_impl_axi_ethernetlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_impl_axi_ethernetlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/brent/prj_microblaze_nexys4_ddr/prj_microblaze_nexys4_ddr.srcs/sources_1/bd/microblaze_impl/ip/microblaze_impl_axi_ethernetlite_0_0/microblaze_impl_axi_ethernetlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_impl_axi_ethernetlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/brent/prj_microblaze_nexys4_ddr/prj_microblaze_nexys4_ddr.srcs/sources_1/bd/microblaze_impl/ip/microblaze_impl_axi_ethernetlite_0_0/microblaze_impl_axi_ethernetlite_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_impl_axi_ethernetlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/brent/prj_microblaze_nexys4_ddr/prj_microblaze_nexys4_ddr.srcs/sources_1/bd/microblaze_impl/ip/microblaze_impl_axi_ethernetlite_0_0/microblaze_impl_axi_ethernetlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_impl_axi_ethernetlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
